---
# Get linux ditribution release
- name: Get release
  hosts: all
  tasks:
    - name: Get release
      ansible.builtin.shell: cat /etc/*-release
      register: release
      changed_when: false
    - name: Display release
      ansible.builtin.debug:
        var: release
