---
# Get linux ditribution release
- name: Get release
  hosts: all
  tasks:
    - name: Get release
      ansible.builtin.command:
        cmd: cat /etc/*-release
        register: release
    - name: Display release
      ansible.builtin.debug:
        var: release
