---
# Get linux release
- name: Get linux release
  hosts: all
  become: true
  tasks:
    - name: Get linux release
      ansible.builtin.ansible_module:
        module: "setup"
        args: "filter=ansible_distribution_release"
      register: release
    - name: Display release
      ansible.builtin.debug:
        var: release
