---
# Linux package updater using yum and dnf
- name: Update packages
  hosts: all
  become: true
  tasks:
    - name: Update using yum
      ansible.builtin.yum:
        name: "*"
        state: latest
    - name: Update using dnf
      ansible.builtin.dnf:
        name: "*"
        state: present
        update_cache: true
