---
# Linux package updater
- name: Update all packages
  hosts: all
  become: true
  tasks:
    - name: Update packages using ansible.builtin.yum
      ansible.builtin.yum:
        update_cache: true
        upgrade: true
